### ISSUE TITLE
[Feature Request]: Detect CPU/AMD/Intel non-supported clients to avoid users installing for a long time and failing

### ISSUE THREAD

**Issue by yoland68** [Comfy-Org/desktop#365]
Prerequisites
  * I have searched the existing issues and checked the recent builds/commits
  * I have read the documentation and this feature is not already available
  * This is a single feature request (not multiple features combined)

Problem StatementNo response

Proposed SolutionNo response

Potential workflow
  1. Go to ....
  2. Press ....
  3. ...

Impact LevelNone

Alternatives ConsideredNo response

Additional informationNo response

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1940-Feature-Request-Detect-CPU-AMD-Intel-non-supported-clients-to-avoid-users-installin-15f6d73d36508125a654efbdf374038c) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
This is resolved now. We auto detect the environment for which pytorch to install, but also let the user set up their own virtual env.
