### ISSUE TITLE
[Bug]: Cannot install Nvidia graphics card card not detected

### ISSUE THREAD

**Issue by DraginEye** [Comfy-Org/desktop#378]
### App Version

![image](https://github.com/user-attachments/assets/72f13fcc-3614-4ba8-b587-2b0b9a8f5f6e)

### Expected Behavior

Run the installer normally

### Actual Behavior

Unable to run because nvidia graphics card not detected.

### Steps to Reproduce

run installer

### Debug Logs

```powershell
unable to get
```

### Browser Logs

unable to get

### Setting JSON

unable to get

### What browsers do you use to access the UI ?

Brave

### Other

windows 10 pro
windows version 22H2
![dxdiag_yyVovWkr0h](https://github.com/user-attachments/assets/8b2beb1f-95ad-4102-af42-606284d68b48)
![ComfyUI_fhzsfpNXHg](https://github.com/user-attachments/assets/be629ff8-150b-4dfa-8e87-fc664b3c2aa6)

**Comment by DraginEye** [comment]
i tried running it in both cmd and powershell both as administrator and it is not a recognized command

**Comment by DraginEye** [comment]
after adding to path it still shows as -1 even after restart, but i was able to get wmic to run regardless and it shows nvidia in the first column as far as i can tell

**Comment by DraginEye** [comment]
![image](https://github.com/user-attachments/assets/b1361299-77cb-4802-bdad-b63138e28cdf)

**Comment by robinjhuang** [comment]
We also default to using nvidia-smi to check if you have those drivers installed. Can improve this discovery process, and perhaps only display a non-blocking warning would be good as well.
