### ISSUE TITLE
[Bug]: Manager should download models in the chosen installation directory

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/desktop#388]
Currently extra_model_config is used to add search paths and desktop co-opted it to define the write path for model downloading.

Need a common way for manager, core, and anything else in the future to know where to place things. Right now we have search paths defined in extra model path yaml, but there's no clear definition of write paths

**Comment by cczw2010** [comment]
yes!
And the models download in the extra_model_path can not show has downloaded in the model manager.
This may result in duplicate models downloaded from the Model Manager and manually downloaded models.

**Comment by robinjhuang** [comment]
Should be resolved in latest release. 

https://github.com/Comfy-Org/desktop/commit/8c9ac593916e8f9d70584444479b31115c90deb4
