### ISSUE TITLE
question about change port 

### ISSUE THREAD

**Issue by yq-xfl** [Comfy-Org/desktop#393]
I downloaded the Windows installation package, successfully installed and ran it. The default port is 8000, and I want to change the port for startup. What should I do?

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1944-question-about-change-port-15f6d73d365081f5bc28ef9a0c87fbd3) by [Unito](https://www.unito.io)

**Comment by huchenlei** [comment]
By default it looks for a free port between 8000 and 9000. You can specify custom port with `COMFY_PORT` env variable.

**Comment by robinjhuang** [comment]
This is also available within the Settings menu under "Server-Config". Closing
