### ISSUE TITLE
[Feature Request]: Set Server to --listen 

### ISSUE THREAD

**Issue by Starnodes2024** [Comfy-Org/desktop#396]
Prerequisites
  * I have searched the existing issues and checked the recent builds/commits
  * I have read the documentation and this feature is not already available
  * This is a single feature request (not multiple features combined)

Problem Statementi found in the code that there is an --listen arg for the server. But i cant find a way to set or enable it. Is it already possible and if yes how? will it be enabled in  a future release? 

Proposed SolutionAdd a --listen setting to the manager or any other place

Potential workflow
  1. Go to ....
  2. Press ....
  3. ...

Impact LevelHigh (Major improvement)

Alternatives ConsideredNo response

Additional informationNo response

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1945-Feature-Request-Set-Server-to-listen-15f6d73d365081b18137c089db7eeceb) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
Hey we can add this to the settings menu. Have you tried setting any of the other server args there?

**Comment by Starnodes2024** [comment]
> Hey we can add this to the settings menu. Have you tried setting any of the other server args there?

Thank you, that would be great. Yes im usint the lowram-setting fot my 8GB GPU it fixed my allowcation on device errors.

**Comment by robinjhuang** [comment]
This is added to the settings menu now.
