### ISSUE TITLE
[Bug]: Cant install on MacBook M1: the default interactive shell is now zsh

### ISSUE THREAD

**Issue by Yaphet2015** [Comfy-Org/desktop#398]
### App Version

ComfyUI 0.3.18 - arm64.dmg

### Expected Behavior

install on my macbook m1 successfully

### Actual Behavior

<img width="932" alt="image" src="https://github.com/user-attachments/assets/418754f2-76ce-40fc-b09d-f7bc71939d2c">

it stucks here. 
And I cant input anything

### Steps to Reproduce

install ComfyUI 0.3.18 - arm64.dmg on Macbook M1, MacOS 15.1

P.S. when I ran `chsh -s /bin/zsh` in my terminal , I got `chsh: no changes made` and nothing happened.

### Debug Logs

```powershell
cant open
```

### Browser Logs

cant open

### Setting JSON

cant open

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-398-Bug-Cant-install-on-MacBook-M1-the-default-interactive-shell-is-now-zsh-1616d73d3650811692c9d76156b55cd1) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
Hey thanks for reporting this. We've seen some reports of this for mac only. If you run 
```
/Applications/ComfyUI.app/Contents/Resources/uv/macos/uv venv --python 3.12.4
```

in your terminal, does it do anything? 

The terminal when it's shows "Setting up Python environment..." is not interactive. Which terminal did you type `chsh -s /bin/zsh` into?

**Comment by dong4j** [comment]
我遇到了同样的问题, 目前的版本的最新的 0.3.30.
我发现 `bash-3.2$` 是我 root 用户的 bash 版本, 意思是 comfyui-desktop 会使用 root 用户配置 python 环境吗?
但是问题是我已经将 zsh 设置成了默认的 shell, 然后启动 comfyui 时却使用了 bash, 导致上面的警告, 然后就没有后续.

我在 root bash 环境下执行了 `/Applications/ComfyUI.app/Contents/Resources/uv/macos/uv venv --python 3.12.4`:

```bash
bash-3.2# /Applications/ComfyUI.app/Contents/Resources/uv/macos/uv venv --python 3.12.4
Using CPython 3.12.4
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
```

看来是没有任何问题的. 我看到这个问题已被关闭了, 但是最新的版本还是如此, 不知道哪个版本才能修复这个问题?

**Comment by robinjhuang** [comment]
We updated the default shell on mac to be zsh now, and also added some bug fixes for `uv python install` that was freezing on some setups. Can you try again?

**Comment by Yaphet2015** [comment]
I am glad to report that the local installation was successful.
