### ISSUE TITLE
[Feature Request]: Does it support the use of a proxy through command - line arguments?

### ISSUE THREAD

**Issue by Ryden-kai** [Comfy-Org/desktop#402]
### Prerequisites

- [X] I have searched the existing issues and checked the recent builds/commits
- [X] I have read the documentation and this feature is not already available
- [X] This is a single feature request (not multiple features combined)

### Problem Statement

![image](https://github.com/user-attachments/assets/1fff084d-67f1-460c-ab73-d7b3e66e4fbd)

### Proposed Solution

![image](https://github.com/user-attachments/assets/1fff084d-67f1-460c-ab73-d7b3e66e4fbd)
Does it support the use of a proxy through command - line arguments?

### Potential workflow

![image](https://github.com/user-attachments/assets/1fff084d-67f1-460c-ab73-d7b3e66e4fbd)
Does it support the use of a proxy through command - line arguments?

### Impact Level

Critical (Blocking my work)

**Comment by z3300200** [comment]
同问，支持这样添加代码

**Comment by huchenlei** [comment]
Why do you need proxy for a desktop app that runs on localhost? Please explain it and reopen a new issue. Thanks!

**Comment by Ryden-kai** [comment]
我已重新打开了一个新问题，麻烦跟进一下： #450

**Comment by Ryden-kai** [comment]
I have reopened a new question, please follow up: #450

**Comment by Ryden-kai** [comment]
> Why do you need proxy for a desktop app that runs on localhost? Please explain it and reopen a new issue. Thanks!

I have reopened a new question, please follow up: #450
