### ISSUE TITLE
NOTICE: Custom node location moving in 0.3.23

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/desktop#411]
In 0.3.18 we made a mistake and shipped a version of ComfyUI-Manager that installs into the app bundle directory. This means that when the app updates, the bundle gets replaced and your custom nodes will be wiped. 

We have a fix ready in the next update that will reinstall custom nodes by parsing your startup logs. This will be going out next *Tuesday (Dec 3rd) 10AM PST* and no action should be required. However if you want to manually fix this you can also move your custom nodes manually:

#### Move your custom nodes 

**From:** `%AppData%\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes` 

**To:**  The directory you chose on the installation screen: `install_directory/custom_nodes` 

#### Replace the current manager

Download and extract the ComfyUI-Manager version shipped in the next release: https://github.com/Comfy-Org/ComfyUI-Manager/archive/refs/tags/0.4.0.zip

Extract it here: `%AppData%\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes`   and rename it to `ComfyUI-Manager` .

#### Move your custom nodes

**From:** `/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes`

**To:**  The directory you chose on the installation screen: `install_directory/custom_nodes` 

#### Replace the current manager

Download and extract the ComfyUI-Manager version shipped in the next release: https://github.com/Comfy-Org/ComfyUI-Manager/archive/refs/tags/0.4.0.zip

Extract it and rename it to `ComfyUI-Manager`: 

Replace the `ComfyUI-Manager` in `/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes`

**Comment by BentJams** [comment]
Thank you for the update, unfortunately this does not fix it for me. Custom nodes still failing after following the steps for macOS.

Here is my log file, let me know if I can help and thanks again!

[Comfy_log.txt](https://github.com/user-attachments/files/17968842/Comfy_log.txt)

**Comment by robinjhuang** [comment]
Looks like you are missing some python packages: 
```
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
ModuleNotFoundError: No module named 'gdown'
ModuleNotFoundError: No module named 'pandas'
```

Try opening the integrated terminal and typing `pip install PyOpenGL PyOpenGL_accelerate` for example. You will need to install all the dependencies that are listed as "missing" from the logs.

**Comment by BentJams** [comment]
Ah ok. I thought ComfyUI Desktop was supposed to install all these things to help less technical folk like myself overcome these barriers.... I will try to figure it out, thank you

**Comment by robinjhuang** [comment]
Not yet, but will happen. Will require lot of work with the registry and the custom node ecosystem in general though. We want to solve that problem in general, not just in Desktop app.

**Comment by robinjhuang** [comment]
0.3.23 has been released so this issue should be fixed.
