### ISSUE TITLE
[Bug]: Manager is missing

### ISSUE THREAD

**Issue by nothingness6** [Comfy-Org/desktop#413]
App VersionThe latest

Expected BehaviorThe manager button should be shown at the top-right corner. 

Actual BehaviorIt doesn't show up :
ComfyUI!UNITO-UNDERSCORE!Desktop ( https://github.com/user-attachments/assets/6bc74afa-6382-49f4-8dfe-ee8173e639bd )

Steps to ReproduceRe-downloaded and clean installed, but nothing has been changed. 

Debug LogsFile "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstanceDiffusion\nodes\load_instance_positionnet_node.py", line 10, in INPUT_TYPES
    "model_filename": (get_model_list(constants.INSTANCE_POSITIONNET_DIR),),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstanceDiffusion\utils\model_utils.py", line 17, in get_model_list
    return os.listdir(path)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI_Tools\\ComfyUI_windows_portable\\ComfyUI\\models\\instance_models\\positionnet_models'

[ERROR] An error occurred while retrieving information for the 'LoadInstanceFusersNode' node.
Traceback (most recent call last):
  File "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstanceDiffusion\nodes\load_instance_fusers_node.py", line 10, in INPUT_TYPES
    "model_filename": (get_model_list(constants.INSTANCE_FUSERS_DIR),),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstanceDiffusion\utils\model_utils.py", line 17, in get_model_list
    return os.listdir(path)
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1950-Bug-Manager-is-missing-15f6d73d36508121b685e6d61ee6f165) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
If the manager button is not present, that probably means there was some issue with it being imported as a custom node. In your logs, do you see anything related to that? Such as "Failed to import ComfyUI-Manager".

Can you check the `comfyui.log` using instructions [here](https://comfyorg.notion.site/ComfyUI-Desktop-User-Guide-1146d73d365080a49058e8d629772f0a#7c5cc3e2c85f44fca191245a97a04517)?

Dev tools is only available in the desktop application itself (from the Help menu).

**Comment by nothingness6** [comment]
> If the manager button is not present, that probably means there was some issue with it being imported as a custom node. In your logs, do you see anything related to that? Such as "Failed to import ComfyUI-Manager".
> 
> Can you check the `comfyui.log` using instructions [here](https://comfyorg.notion.site/ComfyUI-Desktop-User-Guide-1146d73d365080a49058e8d629772f0a#7c5cc3e2c85f44fca191245a97a04517)?
> 
> Dev tools is only available in the desktop application itself (from the Help menu).

Here is the log of the fresh installation :

```
Total VRAM 12288 MB, total RAM 16237 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
[Prompt Server] web root: D:\AI_Tools\ComfyUI_windows_Desktop\ComfyUI\web

Import times for custom nodes:
   0.0 seconds: D:\AI_Tools\ComfyUI_windows_Desktop\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by nothingness6** [comment]
Plus, this is the screenshot of the fresh installation. There are less buttons on the top-right corner :
![ComfyUI_Desktop3](https://github.com/user-attachments/assets/2e198d8d-8bab-45af-86a9-9c6300c4038c)

**Comment by robinjhuang** [comment]
@nothingness6 Should be resolved in the latest version. Is this still an issue?

**Comment by C4l1b3r** [comment]
I have this issue still

**Comment by FelicitasGlow** [comment]
Hello everyone, I'm not a techy person and I will need your help with this. I don't see the manager at my comfyui desktop version. I checked the folder of comfyui and at the custome nodes, it is definitely still there. What should I do?
