### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mikheys** [Comfy-Org/desktop#415]
After setting up the installer and clicking install, everything freezes on the screen with Loading.... and I waited like that for a couple hours. No console appears. A folder with the program is created (430Mb) and a folder with empty folders is created in the path at the beginning of the installer.
image ( https://github.com/user-attachments/assets/31e28be7-a7ef-4c15-9e7f-17664717d9ff )

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1951-Installation-problem-15f6d73d36508194b8ddcd88bcd1f2d0) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
Thanks for reporting this. Can you share your log file? You downloaded 0.3.18 right? Which OS are you on?

**Comment by robinjhuang** [comment]
@mikheys Can you try the latest version?
