### ISSUE TITLE
[Feature]: Add ability to install different versions of Pytorch

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/desktop#421]
Add to initial onboarding flow. Will allow users to install CPU pytorch if desired on Windows, and later RoCM for Linux when we support that.

https://www.figma.com/design/WyLTXXwRnxhdnmqLwDJY60/Comfy's-UI?node-id=996-614&t=VOSuYIPjKiljgWX5-1

If CPU is selected, we should start ComfyUI with --cpu flag on Windows.

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-421-Feature-Add-ability-to-install-different-versions-of-Pytorch-15f6d73d365081d49002e10be737924f) by [Unito](https://www.unito.io)

**Comment by cczw2010** [comment]
and the python version

**Comment by robinjhuang** [comment]
You can select CPU pytorch now.
