### ISSUE TITLE
Add more server side arguments

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/desktop#424]
Add more server side arguments to this ![settings menu](https://blog.comfy.org/content/images/2024/11/image-14.png): 

Arguments to add:
```
--listen
--input-directory
--output-directory
```

Server arguments defined here:
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/cli_args.py

**Comment by huchenlei** [comment]
@robinjhuang Can you link the request of `listen` param? I don't see any reason why you need that to use the desktop app.

**Comment by huchenlei** [comment]
@robinjhuang Gentle ping on follow-up
