### ISSUE TITLE
[Feature Request]: Hope to add VPN proxy setting function

### ISSUE THREAD

**Issue by idesign2018** [Comfy-Org/desktop#428]
Prerequisites
  * I have searched the existing issues and checked the recent builds/commits
  * I have read the documentation and this feature is not already available
  * This is a single feature request (not multiple features combined)

Problem StatementUsers in mainland China cannot download Github plug-ins through Manager. They need to set up the proxy software every time to download Github plug-ins, which is very inconvenient.
The following error message appears:
image ( https://github.com/user-attachments/assets/54575b79-428c-4322-8c01-0f2ddc624154 )

Proposed SolutionI hope to be able to set up the VPN proxy method directly in the ComfyUI settings interface, as shown below:
image ( https://github.com/user-attachments/assets/b606d1af-b620-493b-abe0-dcc21f23f65f )

In this way, you don’t have to switch to the proxy software to set it up. You can directly set up the proxy in ComfyUI and download the Github plug-in

Potential workflow
  1. Go to ....
  2. Press ....
  3. ...

Impact LevelCritical (Blocking my work)

Alternatives ConsideredNo response

Additional informationNo response

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1958-Feature-Request-Hope-to-add-VPN-proxy-setting-function-15f6d73d3650813eb1d6c0188d688a7f) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
This is a great suggestion. Would love to add features to support users in China. Can you provide some more info? 

Some things I don't understand are: How is this different from just running a VPN on the system level? Are you using any mirror urls? Please let us know if there is any other functionality you need.

**Comment by robinjhuang** [comment]
Closing this to track the combined issue here: https://github.com/Comfy-Org/desktop/issues/573

**Comment by huanli11** [comment]
> 在此处关闭此按钮以跟踪组合问题：[#573](https://github.com/Comfy-Org/desktop/issues/573)

It seems you have misunderstood. It's not just an issue during installation. When in use, both installing nodes and downloading models require VPN settings to function properly.
