### ISSUE TITLE
One-click deployment on win10 is successful, and the node used before installation is also very smooth, very cool!

### ISSUE THREAD

**Issue by sjsdwwy** [Comfy-Org/desktop#541]
┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-541-One-click-deployment-on-win10-is-successful-and-the-node-used-before-installation-is-a-1626d73d3650817f901fd960fcc1d630) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
Thank you!
